# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X6KBqFSxvcp8EfTzY7t4DI-hQHOpJgzR
"""

import streamlit as st
import pandas as pd
import io
import matplotlib.pyplot as plt
from mplsoccer import Radar

st.set_option('deprecation.showfileUploaderEncoding', False)

st.title("Comparación de jugadores con gráfico de radar")

@st.cache
def load_data(uploaded_file):
    data = pd.read_excel(uploaded_file)
    return data

def main():
    uploaded_file = st.file_uploader("Carga tus datos en formato Excel", type=['xls', 'xlsx'])
    if uploaded_file is not None:
        data = load_data(uploaded_file)
        team_options = data['Fußballmannschaft'].unique()

        st.sidebar.title("Selecciona los jugadores")

        team1 = st.sidebar.selectbox('Equipo 1', options=team_options, index=0)
        spieler1 = st.sidebar.selectbox('Jugador 1', options=data[data['Fußballmannschaft'] == team1]['Spieler'].unique())

        team2 = st.sidebar.selectbox('Equipo 2', options=team_options, index=1)
        spieler2 = st.sidebar.selectbox('Jugador 2', options=data[data['Fußballmannschaft'] == team2]['Spieler'].unique())

        params_select = st.sidebar.multiselect('Selecciona los parámetros', options=list(data.columns))

        if st.button("Generar gráfico de radar"):
            if not params_select:
                st.error("Selecciona al menos un parámetro.")
            else:
                fig, ax = plt.subplots()
                plot_radar(data, spieler1, spieler2, params_select)
                st.pyplot(fig)

if __name__ == "__main__":
    main()